import ArticleList from '@/components/ArticleList'
import Head from 'next/head'

export default function Home({ articles }) {
  return (
    <>
      <Head>
        <title>Learning Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name='keywords' content='web-development, programming' />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <ArticleList articles={articles} />
    </>
  )
}

export const getStaticProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/posts')
  const articles = await res.json()

  return {
    props: {
      articles
    }
  }
}
